baseurl = "/" # Make sure to end baseurl with a '/'
title = "R • Options Analysis • tastytrade"
#author = "Jason Taylor"
# Shown in the side menu
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Jason Taylor"
  brand = "![Test](/img/metallic_logo.png)"
  googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  #highlightjs = "github"
  #highlightjs = "androidstudio"
  #highlightjs_extra_languages = ["yaml"]
  #dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  # custom_css = ["css/my.css"]
  # custom_js = ["js/my.js"]
  highlightjs = "github"
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "monokai"

  MathJaxCDN = "//cdn.bootcss.com"
  MathJaxVersion = "2.7.1"
  dateFormat = "2006/01/02"

  #[params.piwikAnalytics]
  #  siteid = 2
  #  piwikroot = "//analytics.example.com/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/home/about/"
  #[[menu.main]]
  #  name = "Contact"
  #  pre = "<i class='fa fa-phone fa-fw'></i>"
  #  weight = 4
  #  url = "/home/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.
  twitter = "mechanicalbear"
  email = "jason@themechanicalbear.com"
  linkedin = "jason-taylor-249b115/"
  github = "themechanicalbear"
